UPDATE roles 
SET permissions = ARRAY[
  'USER:CREATE', 'USER:READ', 'USER:UPDATE', 'USER:DELETE',
  'ROLE:CREATE', 'ROLE:READ', 'ROLE:UPDATE', 'ROLE:DELETE',
  'DEPARTMENT:CREATE', 'DEPARTMENT:READ', 'DEPARTMENT:UPDATE', 'DEPARTMENT:DELETE',
  'PATIENT:CREATE', 'PATIENT:READ', 'PATIENT:UPDATE', 'PATIENT:DELETE',
  'APPOINTMENT:CREATE', 'APPOINTMENT:READ', 'APPOINTMENT:UPDATE', 'APPOINTMENT:DELETE',
  'PRESCRIPTION:CREATE', 'PRESCRIPTION:READ', 'PRESCRIPTION:UPDATE', 'PRESCRIPTION:DELETE',
  'WARD:CREATE', 'WARD:READ', 'WARD:UPDATE', 'WARD:DELETE'
],
updated_at = NOW()
WHERE slug = 'hospital_admin' AND is_system_role = true;
